version: "3.8"

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_scheduling_sys
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
  redis:
    image: redis
    container_name: redis_scheduling_sys
    ports:
      - "6379:6379"
